const MSG_ADD = 'MSG_ADD'
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const MSG_DISPATCH = 'MSG_DISPATCH'
const MSG_ADD_ASYNC = 'MSG_ADD_ASYNC';
const DECREMENT_ASYNC = 'DECREMENT_ASYNC';
const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
const MSG_DISPATCH_ASYNC = 'MSG_DISPATCH_ASYNC';
export {
  MSG_ADD,
  INCREMENT,
  DECREMENT,
  MSG_DISPATCH,
  MSG_ADD_ASYNC,
  DECREMENT_ASYNC,
  INCREMENT_ASYNC,
  MSG_DISPATCH_ASYNC
};
